In [10]:
import pandas as pd
import glob

arquivos = glob.glob("data/*.csv")

dados = pd.concat(
    [pd.read_csv(a, sep=';', encoding='utf-8') for a in arquivos],
    ignore_index=True
)

dados

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$)
0,12/10/2024,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99
1,28/10/2024,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00
2,16/11/2024,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49
3,26/11/2024,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08
4,24/01/2025,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33
...,...,...,...,...,...,...,...,...,...
1940,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1941,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39
1942,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1943,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39
1944,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39

In [ ]:
#Datas: converter “DD/MM/AAAA” para tipo date; derivar ano, mês, trimestre,dia da semana.


dados['Data de Compra'] = pd.to_datetime(dados['Data de Compra'], format='%d/%m/%Y')

dados['ano'] = dados['Data de Compra'].dt.year
dados['mes'] = dados['Data de Compra'].dt.month
dados['trimestre'] = dados['Data de Compra'].dt.quarter
dados['dia_semana'] = dados['Data de Compra'].dt.day_name(locale='pt_BR')

dados

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$),ano,mes,trimestre,dia_semana
0,2024-10-12,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99,2024,10,4,Sábado
1,2024-10-28,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00,2024,10,4,Segunda-feira
2,2024-11-16,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49,2024,11,4,Sábado
3,2024-11-26,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08,2024,11,4,Terça-feira
4,2025-01-24,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33,2025,1,1,Sexta-feira
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo
1941,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo
1942,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo
1943,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39,2026,2,1,Domingo
1944,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo

In [12]:
# garantir tipo numérico; tratar vírgula/ponto e campos vazios.

dados['Final do Cartão'] = dados['Final do Cartão'].astype(int)
dados['Valor (em US$)'] = dados['Valor (em US$)'].astype(float)
dados['Cotação (em R$)'] = dados['Cotação (em R$)'].astype(float)
dados['Valor (em R$)'] = dados['Valor (em R$)'].astype(float)

dados

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$),ano,mes,trimestre,dia_semana
0,2024-10-12,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99,2024,10,4,Sábado
1,2024-10-28,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00,2024,10,4,Segunda-feira
2,2024-11-16,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49,2024,11,4,Sábado
3,2024-11-26,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08,2024,11,4,Terça-feira
4,2025-01-24,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33,2025,1,1,Sexta-feira
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo
1941,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo
1942,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo
1943,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39,2026,2,1,Domingo
1944,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo

In [16]:
# parcelas

dados['num_parcela'] = dados['Parcela'].str.split('/').str[0]
dados['num_parcela'] = pd.to_numeric(dados['num_parcela'], errors='coerce')

dados['total_parcelas'] = dados['Parcela'].str.split('/').str[1]
dados['total_parcelas'] = pd.to_numeric(dados['total_parcelas'], errors='coerce')

dados.loc[dados['Parcela'] == 'Única', ['num_parcela', 'total_parcelas']] = 1

dados['total_parcelas'] = dados['total_parcelas'].astype(int)
dados['num_parcela'] = dados['num_parcela'].astype(int)

dados

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$),ano,mes,trimestre,dia_semana,num_parcela,total_parcelas
0,2024-10-12,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99,2024,10,4,Sábado,5,10
1,2024-10-28,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00,2024,10,4,Segunda-feira,5,10
2,2024-11-16,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49,2024,11,4,Sábado,4,10
3,2024-11-26,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08,2024,11,4,Terça-feira,4,4
4,2025-01-24,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33,2025,1,1,Sexta-feira,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo,1,1
1941,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo,1,1
1942,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53,2026,2,1,Domingo,1,1
1943,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39,2026,2,1,Domingo,1,1
1944,2026-02-01,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39,2026,2,1,Domingo,1,1

In [ ]:
#Dimensoes 

# dim data

dim_data = dados[['Data de Compra', 'ano', 'mes', 'trimestre', 'dia_semana']].copy()

dim_data['dia'] = dim_data['Data de Compra'].dt.day

dim_data = dim_data.drop_duplicates().reset_index(drop=True)

dim_data['id_data'] = dim_data.index + 1




# dim titular

dim_titular = dados[['Nome no Cartão', 'Final do Cartão']].copy()

dim_titular = dim_titular.drop_duplicates().reset_index(drop=True)

dim_titular['id_titular'] = dim_titular.index + 1



# dim categoria 

dim_categoria = dados[['Categoria']].copy()

dim_categoria['Categoria'] = dim_categoria['Categoria'].replace('-', 'Não categorizado')

dim_categoria = dim_categoria.drop_duplicates().reset_index(drop=True)

dim_categoria['id_categoria'] = dim_categoria.index + 1


# dim estabelecimento

dim_estabelecimento = dados[['Descrição']].copy()

dim_estabelecimento = dim_estabelecimento.drop_duplicates().reset_index(drop=True)

dim_estabelecimento['id_estabelecimento'] = dim_estabelecimento.index + 1

In [ ]:
# fato 



fato = dados.merge(
    dim_data,
    on=['Data de Compra', 'ano', 'mes', 'trimestre', 'dia_semana'],
    how='left'
)

fato = fato.merge(
    dim_titular,
    on=['Nome no Cartão', 'Final do Cartão'],
    how='left'
)

fato = fato.merge(
    dim_categoria,
    on='Categoria',
    how='left'
)

fato = fato.merge(
    dim_estabelecimento,
    on='Descrição',
    how='left'
)

fato_transacao = fato[[
    'id_data',
    'id_titular',
    'id_categoria',
    'id_estabelecimento',
    'Valor (em R$)',
    'Valor (em US$)',
    'Cotação (em R$)',
    'Parcela',
    'num_parcela',
    'total_parcelas'
]].copy()

fato_transacao.columns = [
    'id_data',
    'id_titular',
    'id_categoria',
    'id_estabelecimento',
    'valor_brl',
    'valor_usd',
    'cotacao',
    'parcela_texto',
    'num_parcela',
    'total_parcelas'
]

In [21]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://usuario:senha@localhost:5432/dw')

dim_data.to_sql('dim_data', engine, index=False, if_exists='replace')
dim_titular.to_sql('dim_titular', engine, index=False, if_exists='replace')
dim_categoria.to_sql('dim_categoria', engine, index=False, if_exists='replace')
dim_estabelecimento.to_sql('dim_estabelecimento', engine, index=False, if_exists='replace')
fato_transacao.to_sql('fato_transacao', engine, index=False, if_exists='replace')

ModuleNotFoundError: No module named 'psycopg2'